### ISSUE TITLE
Enchants have not finished loading

### ISSUE THREAD

**Issue by KuniXl** [bnorick/labbie#20]
There is a similar issue already open, but I don't know if my error is the same error so I post a new issue.
I also get an error "Enchants have not finished loading" when using labbie in the current archnemsis league.
I activated the debug mode in the config file and here is the content of current_run.log:

```
2022-02-05 19:18:09.798 | INFO     | labbie.constants:load:67 - Loading constants from C:\Users\Christian\Desktop\Labbie\Labbie\config\constants.toml specified by default (with 0 overrides).
2022-02-05 19:18:09.799 | INFO     | labbie.config:load:72 - Loading config from C:\Users\Christian\Desktop\Labbie\Labbie\config\config.toml
2022-02-05 19:18:09.800 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.Config __VERSION__=Missing
2022-02-05 19:18:09.800 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.config.UiConfig
2022-02-05 19:18:09.800 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.UiConfig __VERSION__=Missing
2022-02-05 19:18:09.807 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.config.HotkeysConfig
2022-02-05 19:18:09.807 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.HotkeysConfig __VERSION__=Missing
2022-02-05 19:18:09.807 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.config.OcrConfig
2022-02-05 19:18:09.807 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.OcrConfig __VERSION__=Missing
2022-02-05 19:18:09.807 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.bounds.Bounds
2022-02-05 19:18:09.807 | DEBUG    | labbie.mixins:from_dict:207 - labbie.bounds.Bounds __VERSION__=Missing
2022-02-05 19:18:09.808 | DEBUG    | labbie.di.module:provide_config:24 - Loaded config Config(ui=UiConfig(hotkeys=HotkeysConfig(ocr='F2')), ocr=OcrConfig(clear_previous=True, bounds=Bounds(left=335, top=207, right=923, bottom=462)), league=True, daily=True)
2022-02-05 19:18:10.426 | DEBUG    | labbie.resources:needs_update:88 - C:\Users\Christian\Desktop\Labbie\Labbie\data\resources\stats.json.gz needs_update=False cached_hash='vhylmL8Wh9A87219JRJ1jg=='==remote_hash='vhylmL8Wh9A87219JRJ1jg=='
2022-02-05 19:18:10.577 | DEBUG    | labbie.resources:needs_update:88 - C:\Users\Christian\Desktop\Labbie\Labbie\data\resources\items.json.gz needs_update=False cached_hash='yuJNqQXH0zip7LS9hnb6tQ=='==remote_hash='yuJNqQXH0zip7LS9hnb6tQ=='
2022-02-05 19:18:10.726 | DEBUG    | labbie.resources:needs_update:88 - C:\Users\Christian\Desktop\Labbie\Labbie\data\resources\mods.json.gz needs_update=False cached_hash='9vJPY47pGMnkjKj2pKlTpw=='==remote_hash='9vJPY47pGMnkjKj2pKlTpw=='
2022-02-05 19:18:10.728 | DEBUG    | labbie.mixins:notify:90 - labbie.state.AppState notify, event='resources_ready' args=(True,)
2022-02-05 19:18:10.728 | DEBUG    | labbie.mixins:notify:94 - labbie.state.AppState generic notify
2022-02-05 19:18:10.733 | DEBUG    | labbie.ui.app.presenter:_ocr_hotkey_changed:40 - ocr hotkey changed val='F2'
2022-02-05 19:18:10.931 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=SystemTrayIconKey()
2022-02-05 19:18:10.961 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=SearchWindowKey(results=None, clear=False)
2022-02-05 19:18:11.312 | DEBUG    | labbie.ui.search.widget.presenter:populate_view:77 - results=None
2022-02-05 19:18:11.496 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for league
2022-02-05 19:18:11.497 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for daily
2022-02-05 19:18:16.668 | DEBUG    | labbie.mods:mod_trie:112 - Creating Trie
2022-02-05 19:18:16.677 | DEBUG    | labbie.mods:get_mod_list_from_ocr_results:120 - Data from OCR['Trigger Commandment of Ire when Hit', "Adds 1 to 160 Lightning Damage if you haven't", 'Killed Recently', 'Arc deals 12% increased Damage for each time it', 'has Chained', '24% increased Infernal Blow Area of Effect', 'Corrupting Fever has +50% chance to inflict an', 'additional Corrupted Blood Debuff']
2022-02-05 19:18:16.677 | DEBUG    | labbie.ui.app.presenter:screen_capture:73 - curr_enchants=['Arc deals 12% increased Damage for each time it has Chained', '24% increased Infernal Blow Area of Effect', 'Corrupting Fever has +50% chance to inflict an additional Corrupted Blood Debuff']
2022-02-05 19:18:16.677 | DEBUG    | labbie.ui.app.presenter:screen_capture:77 - index=1: enchant='Arc deals 12% increased Damage for each time it has Chained'
2022-02-05 19:18:16.677 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=ErrorWindowKey(exception='Enchants have not finished loading.')
2022-02-05 19:18:16.683 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants have not finished loading.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-Vo48-Db_-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-Vo48-Db_-py3.8\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-Vo48-Db_-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

  File "D:\dev\labbie\src\labbie\ui\app\presenter.py", line 55, in _ocr_hotkey_pressed

> File "D:\dev\labbie\src\labbie\ui\app\presenter.py", line 81, in screen_capture

  File "D:\dev\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.
2022-02-05 19:18:18.245 | DEBUG    | labbie.ui.base:closeEvent:106 - closeEvent, signalling
2022-02-05 19:18:18.254 | DEBUG    | labbie.ui.app.presenter:delete:131 - deleting key=ErrorWindowKey(exception='Enchants have not finished loading.')
2022-02-05 19:18:21.192 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=ErrorWindowKey(exception=EnchantsNotLoaded('Enchants are not loaded.'))
2022-02-05 19:18:21.196 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants are not loaded.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-Vo48-Db_-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-Vo48-Db_-py3.8\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-Vo48-Db_-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

> File "D:\dev\labbie\src\labbie\ui\search\widget\presenter.py", line 105, in on_search_mod

  File "D:\dev\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.
2022-02-05 19:18:26.548 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh daily scrape is downloadable
2022-02-05 19:18:26.548 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable
2022-02-05 19:18:27.796 | DEBUG    | labbie.ui.base:closeEvent:106 - closeEvent, signalling
2022-02-05 19:18:27.805 | DEBUG    | labbie.ui.app.presenter:delete:131 - deleting key=ErrorWindowKey(exception=EnchantsNotLoaded('Enchants are not loaded.'))
2022-02-05 19:18:39.782 | DEBUG    | labbie.ui.base:closeEvent:106 - closeEvent, signalling

```

**Comment by bnorick** [comment]
Thanks for the report, I'll look into it. Do you have daily and league both enabled, or is one disabled?

**Comment by KuniXl** [comment]
I have both activated, but I also tried every other combination of daily and league. I get the same error. I don't know if I get different error logs. If that is interesting, I can also provide you those error logs.

**Comment by KuniXl** [comment]
It works again for me.

**Comment by bnorick** [comment]
Odd, maybe it was the scrapes I uploaded for today.

Let me know if it happens again.
