### ISSUE TITLE
Enchants not loading

### ISSUE THREAD

**Issue by seelroy** [bnorick/labbie#36]
This has been happening for a couple of days now, where it says "enchants are not loaded" or "enchants have not finished loading". Below is my current_run.log.

```
2023-02-11 13:01:16.305 | INFO     | labbie.constants:load:67 - Loading constants from C:\Users\seel\Desktop\PoE\Labbie\config\constants.toml specified by default (with 0 overrides).
2023-02-11 13:01:16.312 | INFO     | labbie.config:load:72 - Loading config from C:\Users\seel\Desktop\PoE\Labbie\config\config.toml
2023-02-11 13:01:16.660 | WARNING  | labbie.mods:_build_helm_mod_info:72 - No trade text found for index=620 mod_variants=[['Venom Gyre has a {0}% chance to keep caught Projectiles fired by using Whirling Blades', ['#'], [25], True]]
2023-02-11 13:01:17.006 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for league
2023-02-11 13:01:17.007 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for daily
2023-02-11 13:01:32.031 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh daily scrape is downloadable
2023-02-11 13:01:32.031 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable
2023-02-11 13:06:32.235 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh daily scrape is downloadable
2023-02-11 13:06:32.249 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable
2023-02-11 13:10:30.031 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants have not finished loading.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\scratch\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

  File "D:\dev\scratch\labbie\src\labbie\ui\search\widget\presenter.py", line 192, in on_screen_capture

> File "D:\dev\scratch\labbie\src\labbie\ui\app\presenter.py", line 85, in screen_capture

  File "D:\dev\scratch\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.
2023-02-11 13:11:32.437 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh daily scrape is downloadable
2023-02-11 13:11:32.453 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable
```

**Comment by bnorick** [comment]
Resolving now, should be good in 30 min.

**Comment by seelroy** [comment]
Can confirm it is working now.
