### ISSUE TITLE
Enchants have not finished loading error when i screen capture.

### ISSUE THREAD

**Issue by Rbrassy** [bnorick/labbie#46]
Hi there,

Getting an error that just says enchants have not finished loading when i try to screen capture at end of lab.

Thoughts?

**Comment by mrDimMak** [comment]
Same goes for me here as a log output with I believe debug enabled:

2023-09-30 19:23:42.703 | INFO     | labbie.constants:load:58 - Overriding constant "Constants.debug" from environment variable (LABBIE_DEBUG), val='1'.
2023-09-30 19:23:42.703 | INFO     | labbie.constants:load:67 - Loading constants from C:\Users\Dim\Documents\Labbie\config\constants.toml specified by default (with 1 overrides).
2023-09-30 19:23:42.704 | INFO     | labbie.config:load:72 - Loading config from C:\Users\Dim\Documents\Labbie\config\config.toml
2023-09-30 19:23:42.704 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.Config __VERSION__=Missing
2023-09-30 19:23:42.704 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.config.UiConfig
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.UiConfig __VERSION__=Missing
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.config.HotkeysConfig
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.HotkeysConfig __VERSION__=Missing
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.config.OcrConfig
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:from_dict:207 - labbie.config.OcrConfig __VERSION__=Missing
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:type_hook:107 - HOOKED labbie.bounds.Bounds
2023-09-30 19:23:42.705 | DEBUG    | labbie.mixins:from_dict:207 - labbie.bounds.Bounds __VERSION__=Missing
2023-09-30 19:23:42.705 | DEBUG    | labbie.di.module:provide_config:24 - Loaded config Config(ui=UiConfig(hotkeys=HotkeysConfig(ocr='\\')), ocr=OcrConfig(clear_previous=True, bounds=Bounds(left=335, top=207, right=923, bottom=462)), league=True, daily=False)
2023-09-30 19:23:43.240 | DEBUG    | labbie.resources:needs_update:88 - C:\Users\Dim\Documents\Labbie\data\resources\stats.json.gz needs_update=False cached_hash='dS2Gn44bUn/BBt8bIBLszA=='==remote_hash='dS2Gn44bUn/BBt8bIBLszA=='
2023-09-30 19:23:43.363 | DEBUG    | labbie.resources:needs_update:88 - C:\Users\Dim\Documents\Labbie\data\resources\items.json.gz needs_update=False cached_hash='n1+jpOEmzcqQ60jrAE8YaA=='==remote_hash='n1+jpOEmzcqQ60jrAE8YaA=='
2023-09-30 19:23:43.486 | DEBUG    | labbie.resources:needs_update:88 - C:\Users\Dim\Documents\Labbie\data\resources\enchants.json.gz needs_update=False cached_hash='O/SEr0+XO4IuO2r838Z5NA=='==remote_hash='O/SEr0+XO4IuO2r838Z5NA=='
2023-09-30 19:23:43.487 | DEBUG    | labbie.mixins:notify:90 - labbie.state.AppState notify, event='resources_ready' args=(True,)
2023-09-30 19:23:43.487 | DEBUG    | labbie.mixins:notify:94 - labbie.state.AppState generic notify
2023-09-30 19:23:43.488 | DEBUG    | labbie.ui.app.presenter:_ocr_hotkey_changed:41 - ocr hotkey changed val='\\'
2023-09-30 19:23:43.582 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=SystemTrayIconKey()
2023-09-30 19:23:43.605 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=SearchWindowKey(results=None, clear=False)
2023-09-30 19:23:43.810 | DEBUG    | labbie.ui.search.widget.presenter:populate_view:77 - results=None
2023-09-30 19:23:43.931 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for league
2023-09-30 19:23:46.943 | DEBUG    | labbie.mods:helm_enchant_trie:54 - Creating helm enchant trie
2023-09-30 19:23:46.945 | DEBUG    | labbie.mods:get_enchant_list_from_ocr_results:62 - Data from OCR['Trigger Commandment of Fury on Hit', "18% reduced Mana Cost of Skills if you've been Hit", 'Recently', '24% increased Lightning Arrow Area of Effect', 'Lightning Golems deal 40% increased Damage', '30% reduced Storm Call Duration']
2023-09-30 19:23:46.945 | DEBUG    | labbie.ui.app.presenter:screen_capture:74 - curr_enchants=['24% increased Lightning Arrow Area of Effect', 'Lightning Golems deal 40% increased Damage', '30% reduced Storm Call Duration']
2023-09-30 19:23:46.945 | DEBUG    | labbie.ui.app.presenter:screen_capture:81 - index=1: enchant='24% increased Lightning Arrow Area of Effect'
2023-09-30 19:23:46.945 | DEBUG    | labbie.ui.app.presenter:show:113 - Getting new presenter for key=ErrorWindowKey(exception='Enchants have not finished loading.')
2023-09-30 19:23:46.951 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants have not finished loading.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\scratch\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

  File "D:\dev\scratch\labbie\src\labbie\ui\search\widget\presenter.py", line 193, in on_screen_capture

> File "D:\dev\scratch\labbie\src\labbie\ui\app\presenter.py", line 85, in screen_capture

  File "D:\dev\scratch\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.
2023-09-30 19:23:48.223 | DEBUG    | labbie.ui.base:closeEvent:106 - closeEvent, signalling
2023-09-30 19:23:48.228 | DEBUG    | labbie.ui.app.presenter:delete:131 - deleting key=ErrorWindowKey(exception='Enchants have not finished loading.')
2023-09-30 19:23:49.228 | DEBUG    | labbie.ui.base:closeEvent:106 - closeEvent, signalling
2023-09-30 19:23:58.950 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable

**Comment by Moyig** [comment]
Got the same issue.

2023-09-30 22:03:32.754 | INFO     | labbie.constants:load:67 - Loading constants from D:\moyig\Documents\labbie\Labbie\config\constants.toml specified by default (with 0 overrides).
2023-09-30 22:03:32.755 | INFO     | labbie.config:load:72 - Loading config from D:\moyig\Documents\labbie\Labbie\config\config.toml
2023-09-30 22:03:34.114 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for league
2023-09-30 22:03:49.159 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable
2023-09-30 22:04:26.183 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants are not loaded.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\scratch\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

> File "D:\dev\scratch\labbie\src\labbie\ui\search\widget\presenter.py", line 105, in on_search_mod

  File "D:\dev\scratch\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.

**Comment by bnorick** [comment]
Should be resolved now.

**Comment by ossu0000** [comment]
Got the same issue.
2023-11-06 20:15:36.383 | INFO     | labbie.constants:load:67 - Loading constants from C:\Users\ossu\Desktop\Labbie\config\constants.toml specified by default (with 0 overrides).
2023-11-06 20:15:36.389 | INFO     | labbie.config:load:72 - Loading config from C:\Users\ossu\Desktop\Labbie\config\config.toml
2023-11-06 20:15:39.279 | INFO     | labbie.enchants:download_or_load:109 - starting refresh task for league
2023-11-06 20:15:54.300 | INFO     | labbie.enchants:_download_when_available:172 - checking if fresh league scrape is downloadable
2023-11-06 20:15:58.624 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants are not loaded.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\scratch\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

> File "D:\dev\scratch\labbie\src\labbie\ui\search\widget\presenter.py", line 105, in on_search_mod

  File "D:\dev\scratch\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.
2023-11-06 20:16:00.139 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants are not loaded.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\scratch\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

> File "D:\dev\scratch\labbie\src\labbie\ui\search\widget\presenter.py", line 141, in on_search_base

  File "D:\dev\scratch\labbie\src\labbie\enchants.py", line 218, in find_matching_bases

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.
2023-11-06 20:16:25.313 | ERROR    | labbie.ui.error.widget.presenter:populate_view:23 - Enchants have not finished loading.
Traceback (most recent call last):

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run

  File "entry_point.py", line 4, in <module>

  File "D:\dev\scratch\labbie\src\labbie\__main__.py", line 73, in main

  File "C:\Users\Brandon Norick\AppData\Local\pypoetry\Cache\virtualenvs\labbie-IkLzptv6-py3.8\lib\site-packages\qasync\__init__.py", line 378, in run_forever

  File "D:\dev\scratch\labbie\src\labbie\ui\app\presenter.py", line 56, in _ocr_hotkey_pressed

> File "D:\dev\scratch\labbie\src\labbie\ui\app\presenter.py", line 85, in screen_capture

  File "D:\dev\scratch\labbie\src\labbie\enchants.py", line 207, in find_matching_enchants

labbie.errors.EnchantsNotLoaded: Enchants are not loaded.

**Comment by bnorick** [comment]
I'll fix it today, my credentials expired for the enchant storage account.

**Comment by Darti7** [comment]
Expired again? :(

**Comment by bnorick** [comment]
Fixed.

I swear I'll automate this next league. Sorry for not getting to it yet, my
mind has been on other things lately. I was joking at exilecon that I
dumped like 8 hours into developing things for Labbie when I got a $5
donation a couple leagues ago, funny how even the slightest show of support
does that.

**Comment by Darti7** [comment]
POGGERS

**Comment by patcolyn** [comment]
Issue is persisting again
![image](https://github.com/bnorick/labbie/assets/13235826/7f91abb4-0d0d-4d8f-bc27-c8a1a750f2b5)

**Comment by bnorick** [comment]
Should be resolved.

Not sure what to think about the league, amazing on the one hand but damn
does Labbie need some love. I imagine it'll probably be a while before I
get it updated.
